In [21]:
import torch
from openbabel import pybel

In [22]:

filename = '/Users/nickgao/Desktop/pythonProject/aimnet2mult/examples/run/model_fid0.jpt'
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = torch.jit.load(filename, map_location=device)

mol_file = '/Users/nickgao/Desktop/pythonProject/local_code_template/test_sdfs/CAMVES_a.sdf'
mol = next(pybel.readfile('sdf', mol_file))

coord = torch.as_tensor([a.coords for a in mol.atoms]).unsqueeze(0).to(device)
numbers = torch.as_tensor([a.atomicnum for a in mol.atoms]).unsqueeze(0).to(device)
charge = torch.as_tensor([mol.charge]).to(device)
mult = torch.as_tensor([mol.spin]).to(device)

_in = dict(
    coord=coord,
    numbers=numbers,
    charge=charge,
    mult=mult,
)

_out = model(_in)

# coord
v_coord = _out['coord']

# numbers(atomic number in periodic table)
v_numbers = _out['numbers']

# charge(total charge of the mol)
v_charge = _out['charge']

# pad_mask
# v_pad_mask = _out['pad_mask']

# _natom (total number of atoms )
v_natom = _out['_natom']

#*********** below are predicted values*********#

# a (atomic feature)
v_a = _out['a']

# d_ij (distance vector: distance between atoms)
v_d_ij = _out['d_ij']

# u_ij (unit distance vector)
# v_u_ij = _out['u_ij']

# gs
v_gs = _out['gs']

# gv
v_gv = _out['gv']

# charges(predicted for each atom)
v_charges = _out['charges']

# energy
v_energy = _out['energy']

# *********most important part about the algorithm
# AIMNet2 type convolution: encoding of local environment which combines geometry of local environment and atomic features.

# Atomic feature vector
afv = _out['a'].flatten(-2, -1)
# AIM layer
aim = _out['aim']



In [23]:
_out['_nb_mode']

tensor(0)

In [24]:
v_energy

tensor([19883.5996], grad_fn=<AddBackward0>)

In [25]:
v_energy

tensor([19883.5996], grad_fn=<AddBackward0>)

In [16]:
mult

tensor([1])

In [17]:
_out['spin_charges']

tensor([[-1.4558, -1.0233, -1.5285, -1.4935, -1.5089, -1.6603, -0.1480, -0.5675,
         -0.5073, -0.7496, -0.7836, -0.4278,  0.1024,  0.3272,  0.1014,  0.1831,
         -0.0683,  0.1224,  0.3791,  0.1188,  0.1522,  0.0103,  0.1822,  0.0240,
         -0.0314, -0.0073,  0.0848,  0.1915,  0.0933,  0.1069, -0.0186,  0.1217,
          0.2046,  0.1017,  0.2534,  0.2964,  0.1992,  0.1569,  0.2938,  0.3112,
          0.2540,  0.2540,  0.3903,  0.3415,  0.3392,  0.1313,  0.2788,  0.6119,
          0.0495,  0.2680,  0.3545,  0.0979,  0.7601,  0.3174,  0.3402,  0.1431,
          0.0161,  0.3521,  0.1641,  0.2290,  0.2999,  0.4898,  0.1997,  0.2559,
          0.3511,  0.0931,  0.1293,  0.3489]], grad_fn=<SubBackward0>)

In [18]:
_out['charges']

tensor([[-1.3398, -1.1676, -1.3661, -1.3598, -1.4590, -1.4403, -0.3355, -0.6478,
         -0.6900, -0.8276, -0.9248, -0.4599,  0.0341,  0.0420,  0.1149,  0.1379,
          0.1264,  0.0358,  0.0471,  0.0756, -0.0468, -0.3020,  0.1246, -0.1093,
         -0.0918,  0.0350, -0.0552, -0.1267,  0.1624, -0.0437, -0.1666,  0.1445,
          0.1475,  0.0496,  0.4730,  0.2567,  0.3315,  0.2326,  0.2824,  0.3419,
          0.4952,  0.7425,  0.3494,  0.2389,  0.2717,  0.1089,  0.5313,  0.4884,
          0.2468,  0.2311,  0.2886,  0.5643,  0.5725,  0.2509,  0.2658,  0.2371,
          0.6952,  0.2928,  0.2384,  0.2018,  0.2752,  0.4581,  0.2782,  0.2649,
          0.2093,  0.3541,  0.3034,  0.3104]], grad_fn=<SumBackward1>)

In [9]:
_out['d_ij']

tensor([[[1.7321, 3.6382, 6.3775,  ..., 4.8060, 3.9737, 4.1460],
         [3.6382, 1.7321, 5.1935,  ..., 3.5660, 2.4526, 4.0693],
         [6.3775, 5.1935, 1.7321,  ..., 8.7193, 7.3548, 8.6613],
         ...,
         [4.8060, 3.5660, 8.7193,  ..., 1.7321, 2.3970, 3.0673],
         [3.9737, 2.4526, 7.3548,  ..., 2.3970, 1.7321, 1.7959],
         [4.1460, 4.0693, 8.6613,  ..., 3.0673, 1.7959, 1.7321]]])

In [10]:
_out['forces'].shape

KeyError: 'forces'

In [59]:
_out['forces']

tensor([[[  149.3583,   346.2549,  -363.8662],
         [  442.6519,   925.7823,  -992.8129],
         [ -169.3563,    32.4389,    69.0470],
         [ -220.2898,  -311.6222,   -95.8973],
         [  837.0601,  -522.2216,   113.0099],
         [   78.6467,   354.6861,   405.0895],
         [ 1433.1299,   503.4658, -1185.0549],
         [   50.7920,   695.1826,  2014.5980],
         [ -361.2667,  -291.9193,   431.2044],
         [  465.0387, -1585.4368,   -75.9908],
         [  -83.1979,  -718.3931, -1735.0349],
         [-1259.9938,  -454.9218,  -843.1440],
         [ -623.9692,  1416.1125,   382.8517],
         [  -27.2419, -1156.9144, -1991.6980],
         [ -337.9153,  2647.7935,  -109.3028],
         [-1378.9401,  -341.2872,   854.3519],
         [  595.8245,  -392.5433,  1660.4919],
         [-1990.7308,  1579.1013,   111.4070],
         [-2941.2358, -1441.0813,  -449.4123],
         [  830.5841,   278.6517,   297.9513],
         [  787.4245,  1647.3066,   -30.3193],
         [ -6

In [60]:
_out['hessian']

tensor([[[[[nan, nan, nan],
           [nan, nan, nan],
           [nan, nan, nan],
           ...,
           [nan, nan, nan],
           [nan, nan, nan],
           [nan, nan, nan]],

          [[nan, nan, nan],
           [nan, nan, nan],
           [nan, nan, nan],
           ...,
           [nan, nan, nan],
           [nan, nan, nan],
           [nan, nan, nan]],

          [[nan, nan, nan],
           [nan, nan, nan],
           [nan, nan, nan],
           ...,
           [nan, nan, nan],
           [nan, nan, nan],
           [nan, nan, nan]]],


         [[[nan, nan, nan],
           [nan, nan, nan],
           [nan, nan, nan],
           ...,
           [nan, nan, nan],
           [nan, nan, nan],
           [nan, nan, nan]],

          [[nan, nan, nan],
           [nan, nan, nan],
           [nan, nan, nan],
           ...,
           [nan, nan, nan],
           [nan, nan, nan],
           [nan, nan, nan]],

          [[nan, nan, nan],
           [nan, nan, nan],
           [